name: Notify Telegram on Release

on:
  release:
    types: [published]

jobs:
  notify:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🎉 New Release Published! 🚀\n\n*Repository:* ${{ github.repository }}\n*Release:* [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})\n\n${{ github.event.release.body }}" \
          -d "parse_mode=Markdown"
